name: Deploy to Dev

on:
  push:
    branches: [dev]

jobs:
  action:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install app dependencies 
        run: npm install

      - name: Install EB CLI and AWS CLI
        run: |
          pip install awsebcli
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: us-east-1

      - name: Initialize Elastic Beanstalk Environment
        run: eb init -r us-east-1

      - name: Configure EB CLI
        run: eb use WebDevelopement-Node-env

      - name: Deploy to Elastic Beanstalk
        run: eb deploy yourEnvironment